defaultPortal: jaygangkun
portals:
  - name: jaygangkun
    portalId: 8831482
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CMnmka7eLhIIAA0ADAAA4AEY-oObBCCB5_4FKO7pDDIZANcA_f7ykdHJuOcAPz4CsDtrcSuvX5dqtDogAAAEQQAAAHgAAAAAAAAAAIABAAAAAAAEwADAB2D-_zFCGQDXAP3-nTe0I4zbWMo71abvhoYefYTYM2U
        expiresAt: '2020-11-20T13:07:38.445Z'
    personalAccessKey: >-
      CiQxZmQ3N2FhNy0wZDZiLTQwMTAtOTc2Yi0zYjdhNjNiNzAwODkQ-oObBBiB5_4FKhkABeaRgmlSl-I0LPJsYjrYp-Jd90sh2YDL
