defaultPortal: jaygangkun
portals:
  - name: jaygangkun
    portalId: 8831482
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CI2NqtvdLhIIAA0ADAAA4AEY-oObBCCB5_4FKO7pDDIZALzulNpBPSzS_xBB8DhWkNhT_XC18fKibTogAAAEQQAAAHgAAAAAAAAAAIABAAAAAAAEwADAB2D-_zFCGQC87pTazqsOopjLMJnXdmTNCA2wdIyssVI
        expiresAt: '2020-11-18T12:53:12.980Z'
    personalAccessKey: >-
      CiQxZmQ3N2FhNy0wZDZiLTQwMTAtOTc2Yi0zYjdhNjNiNzAwODkQ-oObBBiB5_4FKhkABeaRgmlSl-I0LPJsYjrYp-Jd90sh2YDL
