defaultPortal: jaygangkun
portals:
  - name: jaygangkun
    portalId: 8831482
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CJW23-XdLhIIAA0ADAAA4AEY-oObBCCB5_4FKO7pDDIZAC8rjqctUffmXa6CO894Uog_MduoUWCrRTogAAAEQQAAAHgAAAAAAAAAAIABAAAAAAAEwADAB2D-_zFCGQAvK46nkr0DGRIJqIQZztEkVFPR8OA3nVo
        expiresAt: '2020-11-18T18:57:18.109Z'
    personalAccessKey: >-
      CiQxZmQ3N2FhNy0wZDZiLTQwMTAtOTc2Yi0zYjdhNjNiNzAwODkQ-oObBBiB5_4FKhkABeaRgmlSl-I0LPJsYjrYp-Jd90sh2YDL
