defaultPortal: jaygangkun
portals:
  - name: jaygangkun
    portalId: 8831482
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CKGx9LjdLhIIAA0ADAAA4AEY-oObBCCB5_4FKO7pDDIZAGtsGmhCQ2q_xMSakPuN2bhgHCgJMbDnrzogAAAEQQAAAHgAAAAAAAAAAIABAAAAAAAEwADAB2D-_zFCGQBrbBpoPDt_OC1NrkCOjcoEngejBjoEq8o
        expiresAt: '2020-11-17T16:50:09.703Z'
    personalAccessKey: >-
      CiQxZmQ3N2FhNy0wZDZiLTQwMTAtOTc2Yi0zYjdhNjNiNzAwODkQ-oObBBiB5_4FKhkABeaRgmlSl-I0LPJsYjrYp-Jd90sh2YDL
